### ISSUE TITLE
Out of bounds exception

### ISSUE THREAD

**Issue by IrisBC** [vaind/properties.dart#9]
Hi Ivan, 
I have been trying to intregrate your tool into my application and have reached an out of bounds exception. I was following the instructions to use it and run an error when truing to get the properties from my file with `Properties p = Properties.fromFile(path);`.

An example of error trace is:
```
"LogLevel.ERROR"     "RangeError (index): Invalid value: Not in inclusive range 0..112: -1"     "#0      List.[] (dart:core-patch/growable_array.dart:264:36)
I/flutter (11792): #1      Line._isProperty (package:properties/src/properties_parser.dart:237:46)
I/flutter (11792): #2      Line._init (package:properties/src/properties_parser.dart:137:17)
I/flutter (11792): #3      new Line (package:properties/src/properties_parser.dart:119:5)
I/flutter (11792): #4      PropertiesParser._getLines (package:properties/src/properties_parser.dart:47:20)
I/flutter (11792): #5      PropertiesParser.parse (package:properties/src/properties_parser.dart:10:14)
I/flutter (11792): #6      Properties._initFromFile (package:properties/properties.dart:107:23)
I/flutter (11792): #7      new Properties.fromFile (package:properties/properties.dart:68:5)
I/flutter (11792): #8      FileManager.loadPendingSessions.<anonymous closure> (package:able_care/services/file_manager.dart:998:39)
I/flutter (11792): <asynchronous suspension>
I/flutter (11792): "
```

This seems to come from the fragment:
```dart 
   for (var i = 0; i < line.length; i++) {
      if (line[i] == Properties.EQUAL && line[i - 1] != Properties.BACKSLASH) {
        return true;
      }
    }
````
I am guessing if the first int is Properties.EQUAL with i=0, then it tries to look for position 0-1 = -1 Out of bounds.
I am not sure how I reached the case in which the first item is a `=` after registering a key with `p.add(Constant.KeyNames.LocalPropertySID, response.toString(), true)` (the constant is a string, so the key should not have been empty either.

Is there something I am missing or implementing incorrectly? Anyhow, controlling that exception could be healthy for your code as well.

Have a nice day,
Iris

**Comment by vaind** [comment]
Yes, looks like a bug. To be clear, I barely know the code, I just had to use it once and have taken it over from the original author to make an updated to null-safety.

Anyway, is it possible for you to share the properties file so we can see the input it fails on?
